src/features/resume/index.tsx
=> fix: resume page

src/features/resume/data/struct-mapper.ts
=> fix: ts type

src/routes/_authenticated/interview/prepare.tsx, src/routes/_authenticated/interview/session.tsx
=> fix: mobile interview page

src/features/home/api.ts
=> refactor: notification desc

src/components/support-dialog.tsx
=> fix: submit btn loading

src/features/home/index.tsx
=> fix: application card style

src/features/interview/index.tsx
=> refactor(interview): 移除面试结束时的节点提交逻辑- 删除了面试结束时自动提交当前节点的代码逻辑

src/features/resume-upload/types/struct-info.ts, src/features/resume/components/dynamic-basic-form.tsx, src/features/resume/data/struct-mapper.ts, src/features/resume/index.tsx
=> fix: tag input style

src/features/jobs/index.tsx
- 移除了不必要的 index 参数
- 将 openingsCount 替换为 job.referralBonus，并处理了空值情况- 优化了代码结构，提高了代码的可读性和维护性
关闭：#
=> refactor(jobs): 重构工作列表渲染逻辑

src/components/ui/rich-text.tsx, src/features/jobs/components/job-detail-content.tsx
- 引入 RichText 组件来处理和展示职位描述
- 增加 HTML 内容的清理和安全处理
- 改进纯文本描述的换行显示
- 统一和优化描述内容的样式
关闭：#
=> feat(jobs): 优化职位详情页面的描述展示

src/assets/images/logo-circle.svg
=> feat: 添加圆形 logo 图片- 新增 logo-circle.svg 文件- 使用 SVG 格式设计圆形 logo

src/components/layout/authenticated-layout.tsx, src/components/livekit/agent-control-bar.tsx, src/features/interview/index.tsx, src/features/interview/session-view.tsx, src/features/jobs/index.tsx, src/routes/_authenticated/interview/session.tsx
- 将"寻找与你匹配的远程/合约职位"修改为"寻找与你匹配的工作机会"
- 优化页面描述，使其更加通用和吸引人
关闭：#
=> refactor(jobs): 更新职位列表页面的描述文本

src/features/jobs/index.tsx
=> fix: 修复职位列表数量超出一屏无法滚动问题

src/components/layout/nav-user.tsx, src/components/profile-dropdown.tsx, src/features/home/index.tsx
- 应用列表添加 padding 和底部渐变效果
- 隐藏用户邮箱显示
- 统一用户信息展示格式
关闭：#
=> refactor(home): 优化首页应用列表样式和用户信息显示

index.html, src/components/layout/app-sidebar.tsx
- 更新侧边栏展开态的 logo 和文案布局
- 新增收起态的小图标样式
- 更新网站 favicon 为 logo-circle.svg
- 简化网页标题和描述
关闭：#
=> refactor(layout): 优化侧边栏展开/收起态的视觉样式

src/components/ui/sheet.tsx, src/features/interview/index.tsx, src/features/interview/prepare.tsx
- 优化面试房间连接逻辑，增加对特定错误码的处理
- 改进职位描述的展示方式，使用 RichText 组件
- 调整面试准备页面的样式，添加 no-scrollbar 类
- 修复 Sheet 组件关闭按钮的样式问题
关闭：#
=> feat(interview): 优化面试房间连接和职位描述展示

.github/workflows/deploy.yml, env.local.example, package.json, pnpm-lock.yaml, src/lib/apm.ts, src/main.tsx, src/stores/authStore.ts
- 添加 APM 相关环境变量
- 实现 APM 初始化及用户、认证信息的同步
- 在应用生命周期中集成 APM 监控
- 新增 apm.ts 文件实现相关功能
关闭：#
=> feat(apm): 集成应用性能监控系统

src/lib/api.ts, src/lib/apm.ts
- 在 API 请求拦截器中增加业务错误上报逻辑
- 新增 reportApiBusinessError 函数用于错误上报
- 优化错误信息的序列化处理
关闭：#
=> feat(apm): 添加 API 业务错误上报功能

src/features/interview/prepare.tsx
=> fix(interview): 增强音频设备切换的错误处理和日志记录

src/features/interview/prepare.tsx
- 移除了预计 48 小时内通知的描述
- 简化了审核中状态下的提示信息
关闭：#
=> docs(interview): 修改面试结束后的通知文案

src/features/interview/prepare.tsx, src/lib/devices.ts
- 在没有匹配的默认设备时，确保返回设备列表中的第一个设备ID
- 提升设备选择的灵活性和用户体验
=> fix(interview): 改进默认设备ID的返回逻辑

src/features/interview/prepare.tsx
- 移除在设置首选设备ID后更新显示设备ID的逻辑
- 添加调试日志以便于跟踪首选扬声器设备的状态
关闭：#
=> fix(interview): 优化扬声器设备ID的设置逻辑

src/features/interview/prepare.tsx
- 在设置首选设备ID后，确保在成功后更新显示设备ID
- 增加对displaySpkDeviceId的依赖，优化设备ID的管理逻辑
- 保留调试日志以便于跟踪设备状态
关闭：#
=> fix(interview): 更新扬声器设备ID的设置逻辑

src/features/jobs/index.tsx
=> fix: btn style

src/features/jobs/index.tsx
=> fix: btn font weight

src/features/jobs/index.tsx
=> fix: btn font size

src/features/interview/components/local-camera-preview.tsx, src/features/interview/index.tsx, src/hooks/use-camera-status-detection.ts
- 在面试页面中，改进了定时器的管理逻辑，确保在组件卸载时正确清理定时器
- 在本地摄像头预览组件中，添加了摄像头状态检测功能，优化了黑屏检测的启动和停止逻辑
- 更新了确认摄像头状态正常的按钮逻辑，确保在检测到问题时禁用按钮
关闭：#
=> fix(interview): 优化面试页面和本地摄像头预览组件

src/features/interview/index.tsx, src/features/interview/prepare.tsx, src/features/interview/session-view.tsx, src/features/jobs/index.tsx, src/lib/api.ts, src/lib/apm.ts
=> Fix conflict 0916

src/features/resume/data/schema.ts, src/features/resume/index.tsx
=> fix: 添加简历表单校验限制

src/features/resume/data/struct-mapper.ts
=> fix: email default value

src/features/interview/index.tsx, src/lib/apm.ts
- 在面试页面中引入设备信息上报功能，记录音频和视频输入输出状态
- 增加房间连接错误的上报功能，提升错误追踪能力
- 更新 APM 模块，添加相应的上报函数
=> feat(interview): 添加设备信息上报和连接错误处理

src/lib/api.ts
=> fix: 增加简历保存失败提示

src/features/finish/index.tsx
链接内容为"参与体验调研>>"，现已从代码中删除。
关闭：#
=> feat(finish): 移除页面中的体验调研链接移除了完画面中的体验调研链接，该链接指向飞书表单。

src/features/interview/prepare.tsx
移除旧版按钮组件，更新新版面试间按钮点击事件及显示文本。
同时增加调试日志以辅助排查连接问题。
关闭：#
=> fix(interview): 调整新版面试间按钮逻辑与文案

src/features/interview/prepare.tsx, src/routes/_authenticated/interview/prepare.tsx
- 调整设备检查区域的网格和弹性布局组合
- 更新左右内容区域在不同屏幕尺寸下的占比
- 移除移动端全屏遮罩逻辑
- 注释掉移动端检测相关代码- 优化操作区域在大屏下的固定定位表现
- 改进职位标题区域的响应式显示效果
关闭：#
=> feat(interview): 测试用，优化面试准备页面响应式布局

src/features/finish/index.tsx
=> feat(finish): 在导航中添加选项卡参数以支持记录视图

src/features/home/index.tsx, src/features/jobs/index.tsx, src/features/resume/index.tsx
=> feat(home, jobs, resume): 调整标题右边距，优化页面布局

src/features/mock-interview/components/mock-interview-list.tsx
=> fix(mock-interview): 调整分类按钮最小宽度以优化布局

src/features/interview/api.ts, src/features/interview/components/questionnaire-collection.tsx, src/features/interview/prepare.tsx
=> feat(interview): 更新问卷相关术语为“问卷收集”，优化问卷节点处理逻辑，添加未完成和拒绝节点的处理

src/features/jobs/index.tsx, src/features/mock-interview/components/mock-interview-records.tsx, src/features/mock-interview/types.ts
=> feat(jobs, mock-interview): 优化职位列表和面试记录组件，调整样式和结构

src/features/interview/prepare.tsx
=> feat(interview): 在准备面试页面中添加视图模式设置逻辑

src/features/interview/components/questionnaire-collection.tsx
=> fix(interview): 调整问卷收集组件的高度样式，优化加载状态显示

.github/workflows/deploy.yml
- 在部署工作流中新增 VITE_XPERT_STUDIO_DOMAIN 变量配置
- 确保构建过程中正确注入该环境变量- 支持应用运行时访问 Xpert Studio 域名配置
关闭：#
=> feat(workflow): 添加 VITE_XPERT_STUDIO_DOMAIN 环境变量

src/main.tsx
- 从URL参数中获取并存储分享用户ID
- 在设置Apm上下文时包含分享用户ID
关闭：#
=> feat(main): 增加分享用户ID的存储和上下文设置

src/features/interview/api.ts, src/features/interview/components/support-dialog.tsx
=> feat: 寻求帮助支持上传图片

src/features/mock-interview/tabs-page.tsx
=> fix: 删除无用代码

src/components/layout/nav-group.tsx, src/components/layout/nav-user.tsx
=> feat: sidebar样式修改

src/features/interview/prepare.tsx
- 在感谢页面中添加了指向职位列表的超链接 -为职位列表链接添加了点击事件处理，防止默认行为
- 使用 window.location.href 实现页面跳转以确保正确导航
- 优化了文本布局，提升用户阅读体验- 保持了原有的页面结构和样式设计
关闭：#
=> feat(interview): 添加职位列表链接并优化页面跳转逻辑
